version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: validate
          command: npm run validate
      - run:
          name: release
          command: npm run semantic-release
